// [bloco10-blog] Manifesto dos posts — mantém a lista/índice leve sem
// precisar carregar todo o markdown só pra montar o /blog. O conteúdo
// completo de cada post vive em content/blog/{slug}.md.
export const POSTS = [
  {
    slug: 'quanto-tempo-demora-processo-trabalhista',
    title: 'Quanto tempo demora um processo trabalhista?',
    excerpt: 'Prazos reais por fase — da reclamação à execução — e o que mais atrasa um processo na Justiça do Trabalho.',
    area: 'Direito Trabalhista',
    date: '28 jun 2026',
    ctaTo: '/trabalhista',
    ctaLabel: 'Calcular minhas verbas rescisórias grátis',
  },
  {
    slug: 'como-funciona-garantia-legal-produto-com-defeito',
    title: 'Produto com defeito: como funciona a garantia legal (não é a do fabricante)',
    excerpt: 'A diferença entre garantia legal e garantia contratual, os prazos do CDC e o que fazer quando a loja empurra pro fabricante.',
    area: 'Direito do Consumidor',
    date: '29 jun 2026',
  },
  {
    slug: 'imposto-de-renda-aluguel-declarar',
    title: 'Aluguel recebido precisa declarar no Imposto de Renda? Como calcular',
    excerpt: 'Carnê-leão, alíquotas, o que pode ser deduzido e os erros mais comuns de quem vive de renda de aluguel.',
    area: 'Direito Tributário',
    date: '30 jun 2026',
  },
  {
    slug: 'despejo-por-falta-de-pagamento-prazo',
    title: 'Despejo por falta de pagamento: quanto tempo o inquilino tem antes de sair',
    excerpt: 'O rito da ação de despejo, o prazo de desocupação voluntária e quando cabe liminar.',
    area: 'Direito Civil',
    date: '30 jun 2026',
  },
  {
    slug: 'pensao-alimenticia-como-e-calculada',
    title: 'Como é calculada a pensão alimentícia no Brasil',
    excerpt: 'Não existe percentual fixo em lei — entenda o binômio necessidade/possibilidade e os critérios que o juiz usa.',
    area: 'Direito de Família',
    date: '01 jul 2026',
  },
  {
    slug: 'empresa-vazou-meus-dados-o-que-fazer',
    title: 'Minha empresa vazou meus dados pessoais — o que a LGPD garante',
    excerpt: 'Direitos do titular, o papel da ANPD e como pedir reparação quando um vazamento causa dano.',
    area: 'Direito Digital',
    date: '01 jul 2026',
  },
  {
    slug: 'compra-online-produto-nao-chegou-reembolso',
    title: 'Comprei online e o produto não chegou: prazo de reembolso e o que fazer',
    excerpt: 'O que o CDC garante quando a entrega atrasa: cumprimento forçado, produto equivalente ou reembolso integral — e o prazo de arrependimento de 7 dias.',
    area: 'Direito do Consumidor',
    date: '02 jul 2026',
  },
  {
    slug: 'demissao-sem-justa-causa-verbas-rescisorias',
    title: 'Fui demitido sem justa causa: quais verbas rescisórias tenho direito',
    excerpt: 'Saldo de salário, aviso prévio, férias, 13º, FGTS com multa de 40% — a lista completa pra conferir se o TRCT bateu certo.',
    area: 'Direito Trabalhista',
    date: '03 jul 2026',
    ctaTo: '/trabalhista',
    ctaLabel: 'Calcular minhas verbas rescisórias grátis',
  },
  {
    slug: 'guarda-compartilhada-como-funciona',
    title: 'Guarda compartilhada: como funciona na prática e quem decide onde o filho mora',
    excerpt: 'Guarda compartilhada não é dividir o tempo ao meio — entenda a diferença entre guarda e residência, e como o juiz decide quando não há acordo.',
    area: 'Direito de Família',
    date: '04 jul 2026',
  },
  {
    slug: 'golpe-pix-como-reaver-dinheiro',
    title: 'Caí num golpe pelo Pix: dá pra reaver o dinheiro? O que fazer',
    excerpt: 'Como funciona o Mecanismo Especial de Devolução (MED) do Banco Central, os prazos envolvidos e por que agir rápido aumenta as chances de recuperação.',
    area: 'Direito Digital',
    date: '05 jul 2026',
  },
  {
    slug: 'quanto-tempo-demora-beneficio-inss',
    title: 'Quanto tempo demora pra sair um benefício do INSS',
    excerpt: 'Os prazos legais por tipo de benefício (45, 60 ou 90 dias), o que fazer quando o INSS estoura o prazo e por que você não perde o retroativo.',
    area: 'Direito Previdenciário',
    date: '06 jul 2026',
  },
  {
    slug: 'vizinho-barulho-o-que-diz-a-lei',
    title: 'Vizinho fazendo barulho: o que a lei diz e como formalizar a reclamação',
    excerpt: 'O direito de vizinhança do Código Civil, se existe horário do silêncio, e o passo a passo pra formalizar — do síndico até a ação judicial.',
    area: 'Direito Civil',
    date: '07 jul 2026',
  },
  {
    slug: 'direito-de-arrependimento-compra-online-7-dias',
    title: 'Comprei online e me arrependi: como funciona o prazo de 7 dias',
    excerpt: 'O direito de arrependimento do CDC em compras à distância — o que cobre, o que não cobre, e como é diferente de uma troca por defeito.',
    area: 'Direito do Consumidor',
    date: '08 jul 2026',
  },
  {
    slug: 'hora-extra-nao-paga-como-calcular-cobrar',
    title: 'Hora extra não paga: como calcular e cobrar o que a empresa deve',
    excerpt: 'Adicional mínimo, reflexo em 13º/férias/FGTS, e os sinais mais comuns de que a empresa está calculando errado.',
    area: 'Direito Trabalhista',
    date: '09 jul 2026',
    ctaTo: '/trabalhista',
    ctaLabel: 'Calcular minhas verbas rescisórias grátis',
  },
  {
    slug: 'divorcio-tipos-prazo-partilha-de-bens',
    title: 'Divórcio no Brasil: tipos, prazo e o que muda na partilha de bens',
    excerpt: 'Extrajudicial x judicial, o que entra na partilha conforme o regime de bens, e o que continua igual em relação aos filhos.',
    area: 'Direito de Família',
    date: '10 jul 2026',
  },
  {
    slug: 'aposentadoria-por-idade-x-tempo-de-contribuicao',
    title: 'Aposentadoria por idade x tempo de contribuição: qual a diferença',
    excerpt: 'Como funcionam as regras de transição da reforma da previdência e por que vale simular mais de uma antes de pedir o benefício.',
    area: 'Direito Previdenciário',
    date: '11 jul 2026',
  },
  {
    slug: 'acidente-de-transito-como-funciona-a-indenizacao',
    title: 'Sofri um acidente de trânsito: como funciona a indenização',
    excerpt: 'O que pode ser cobrado, o papel do seguro obrigatório, e os passos práticos pra documentar o acidente logo depois que acontece.',
    area: 'Direito Civil',
    date: '12 jul 2026',
  },
  {
    slug: 'fui-preso-em-flagrante-quais-meus-direitos',
    title: 'Fui preso em flagrante: quais são os meus direitos',
    excerpt: 'Direito ao silêncio, à assistência de advogado e à audiência de custódia — o que a lei garante desde o momento da prisão.',
    area: 'Direito Penal',
    date: '13 jul 2026',
  },
  {
    slug: 'negativado-indevidamente-o-que-fazer',
    title: 'Fui negativado indevidamente: o que fazer e como pedir indenização',
    excerpt: 'O que caracteriza negativação indevida, o passo a passo pra contestar, e por que outras "sujeiras" no nome podem afetar a indenização.',
    area: 'Direito Digital',
    date: '14 jul 2026',
  },
  {
    slug: 'imovel-na-planta-atraso-na-obra-quais-direitos',
    title: 'Comprei um imóvel na planta e a obra atrasou: quais meus direitos',
    excerpt: 'A cláusula de tolerância de 180 dias, o que pode ser cobrado depois dela, e o que fica de fora mesmo com atraso comprovado.',
    area: 'Direito Imobiliário',
    date: '15 jul 2026',
  },
  {
    slug: 'plano-de-saude-negou-procedimento-o-que-fazer',
    title: 'Plano de saúde negou um procedimento: o que a lei garante',
    excerpt: 'Quando a negativa costuma ser considerada abusiva, o passo a passo pra contestar, e quando vale a pena pedir liminar judicial.',
    area: 'Direito da Saúde',
    date: '16 jul 2026',
  },
  {
    slug: 'imposto-de-renda-autonomo-mei-o-que-muda',
    title: 'Declarar Imposto de Renda como autônomo ou MEI: o que muda',
    excerpt: 'Carnê-leão x DAS, os erros mais comuns que levam à malha fina, e quando vale migrar de MEI pra outro regime.',
    area: 'Direito Tributário',
    date: '17 jul 2026',
  },
  {
    slug: 'como-abrir-mei-passo-a-passo-quando-migrar',
    title: 'Como abrir um MEI: passo a passo e quando vale migrar pra ME',
    excerpt: 'O processo completo de formalização, as obrigações mensais depois de aberto, e os sinais de que é hora de sair da categoria.',
    area: 'Direito Empresarial',
    date: '18 jul 2026',
  },
  {
    slug: 'cobranca-indevida-cartao-credito-como-contestar',
    title: 'Cobrança indevida no cartão de crédito: como contestar e pedir estorno',
    excerpt: 'Os tipos mais comuns de cobrança errada, o processo de contestação (chargeback) e o prazo que você tem pra agir.',
    area: 'Direito do Consumidor',
    date: '19 jul 2026',
  },
];
